development:
  adapter: postgresql
  encoding: utf8
  database: dst_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: dst_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: dst_production
  pool: 5
  username: 
  password: